version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    reviewers:
      - "tmfg/digitraffic-tis-solita"
      - "peteras"
  # keep used GitHub Actions up to date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "tmfg/digitraffic-tis-solita"
      - "peteras"
