version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    reviewers:
      - "tmfg/digitraffic-tis-solita"
      - "peteras"
    groups:
      dev-deps:
        dependency-type: "development"
      prod-deps:
        dependency-type: "production"
  # keep used GitHub Actions up to date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "tmfg/digitraffic-tis-solita"
      - "peteras"
    groups:
      actions-deps:
        patterns:
          - "*"
