name: "Build and push to GHCR"
on:
  workflow_run:
    workflows: [ "Release new version" ]
    types:
      - completed

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

# Most of this is taken from https://docs.github.com/en/actions/publishing-packages/publishing-docker-images

jobs:
  BuildAndPushImageToECR:
    name: "Build and Push to GHCR"
    runs-on: ubuntu-latest

    if: ${{ github.actor != 'dependabot[bot]' }}

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Log in to the Container registry
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract CURRENT version
        id: version_tag
        uses: WyriHaximus/github-action-get-previous-tag@61819f33034117e6c686e6a31dba995a85afc9de # v2.0.0
        with:
          prefix: v

      - name: Format version tag
        id: version
        run: |
          echo "VERSION=$(echo ${{ steps.version_tag.outputs.tag }} | cut -c2-)" >> $GITHUB_ENV

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@80c7e94dd9b9319bd5eb7a0e0fe9291e23a2a2e9 # v6.1.0
        with:
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=semver,pattern={{major}}.{{minor}}.{{patch}},value=${{ env.VERSION }},enable={{is_default_branch}}
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build, tag, and push image to GHCR
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
